select * from usuario;
select * from funcao;
select * from tipo_membro;
select * from tipo_evento;
select * from entidade;
select * from membro;
select * from campanha;
select * from contribuinte;
select * from lancamento_campanha;